version: '3.7'
services:
  grafana:
    image: grafana/grafana:latest
    environment:
      GF_PLUGINS_ALLOW_LOADING_UNSIGNED_PLUGINS: centreon-datasource
    volumes:
      - ./dist:/var/lib/grafana/plugins/centreon-datasource
      - grafana_data:/var/lib/grafana
    ports:
      - "3000:3000"

volumes:
  grafana_data: